print("welcome to Space Dungeon")
print("Press Enter To Continue")
input()
print("Choose your Class")
print("Space Duck")
print("That One Human")
print("Sexy Alien")
classes = input()
print("Delegate Points. You have 100 to spend. ")
print("How Many points to magic")
magic = input()
print("How many points to attack")
attack =input()
print("What is your name")
name = input()
print("welcome " +name+ "You have "+magic+" magic points and "+attack+ " attack points")
print("and is "+classes+" class.")
