print('&&& Madlibs &&&')"""come back to this after i learn functions"""
print('==================================')
print('There once was a _____ From _____. ')
print(' Who dreamed that it was ____ a _____.')
print('it woke with a ____ ,in the middle of the night,')
print(' to see that its dream had come true.')
print('===================================')
print('please give a noun for line one')
line_one= str(input())
print('Would you like to see so far?')
input()
    # if: input()= yes
    #     print('==================================')
    #     print('There once was a '+ line_one+'From _____. ')
    #     print(' Who dreamed that it was ____ a _____.')
    #     print('it woke with a ____ ,in the middle of the night,')
    #     print(' to see that its dream had come true.')
    #     print('===================================')
    #     print('would you like to change line one?')
    #     input()

print('please give a place for line two')
line_two= str(input())
print('Would you like to see so far?')
input()
    # if: input()= yes
    #     print('==================================')
    #     print('There once was a '+ line_one+'From ' line_two)
    #     print(' Who dreamed that it was ____ a _____.')
    #     print('it woke with a ____ ,in the middle of the night,')
    #     print(' to see that its dream had come true.')
    #     print('===================================')
    #     print('would you like to change line one?')
    #     input()

    print('please give a adjective for line three')
    line_three= input()
    print('Would you like to see so far?')
    input()

    # if: input()= yes
    #     print('==================================')
    #     print('There once was a '+ line_one+'From '+ line_two)
    #     print(' Who dreamed that it was'+line_three+ 'a _____.')
    #     print('it woke with a ____ ,in the middle of the night,')
    #     print(' to see that its dream had come true.')
    #     print('===================================')
    #     print('would you like to change line one?')
    #     input()

print('please give a noun for line four')
line_four= str(input())
print('Would you like to see so far?')
input()

    # if: input()= yes
    #     print('==================================')
    #     print('There once was a '+ line_one+'From '+ line_two)
    #     print(' Who dreamed that it was'+line_three+ 'a '+line_four)
    #     print('it woke with a ____ ,in the middle of the night,')
    #     print(' to see that its dream had come true.')
    #     print('===================================')
    #     print('would you like to change line one?')
    #     input()

print('please give a adjective for line five')
line_five= str(input())
print('Would you like to see so far?')
input()

    # if: input()= yes
    #     print('==================================')
    #     print('There once was a '+ line_one+'From '+ line_two)
    #     print(' Who dreamed that it was'+line_three+ 'a '+line_four)
    #     print('it woke with a'+line_five+ ',in the middle of the night,')
    #     print(' to see that its dream had come true.')
    #     print('===================================')
    #     print('would you like to change line one?')
    #     input()

print('Here is your Madlibs')
print('==================================')
print('There once was a '+ line_one+'From '+ line_two)
print(' Who dreamed that it was'+line_three+ 'a '+line_four)
print('it woke with a'+line_five+ ',in the middle of the night,')
print(' to see that its dream had come true.')
print('===================================')
